name = "Vibrio_parahaemolyticus_K"
keyword = "vpar_k"
genbank = "VibrioPara_Kaptivedb_K.gbk"
organism = "Vibrio parahaemolyticus"
taxon = 670
antigen = "Capsular polysaccharide"
pathway = "Wzx/Wzy-dependent"
prefix = "K"
version = "1.0.1"
id_threshold = 82.5
doi = [ "10.1099/mgen.0.001007",]
owner = "aldertzomer"
repo = "vibrio_parahaemolyticus_genomoserotyping"
branch = "main"

[contact]
"Aldert Zomer" = "a.l.zomer@uu.nl"
